### ISSUE TITLE
Stop using pytorch?

### ISSUE THREAD

**Issue by markroxor** [jellAIfish/fromscratchtoml#32]
Why not to use `pytorch` ?
* beta
* too resource expensive - (almost 470MB package) with no `pip` packages for Travis.
* couldn't install the latest build without caching (or I ran out of memory error).
* the latest update almost [broke our every test case](https://travis-ci.org/jellAIfish/fromscratchtoml/builds/374572949).
* a lot of features are missing, therefore we are still relying on `numpy`. This involves a lot of typecasting back and forth which pollutes the code.
* except for `cuda` support it adds nothing more.
* #31  A small typecasting issue which was nearly untraceable got me scratching my head for over three days.
* I had to update it everywhere just to use a very small feature. [#7251](https://github.com/pytorch/pytorch/issues/7251)
* We are not using its core functionalities anyways.

**Comment by markroxor** [comment]
@somnat @dikshant2210 revert all your codes to avoid using torch.

**Comment by SsnL** [comment]
I just want to say that your output in #31 clearly states that one np ndarray is `float32` and another is not. I don't think pytorch is to blame here.

And I also skimmed through your test failures. It seems that most of them are easy fixes, and each fix probably will solve more than 1 errors.

**Comment by markroxor** [comment]
I am not blaming pytorch. I believe it is a bit of an overkill for our library. We are not using it's core functionalities. We are using it only for performing mathematical operations. Eg. In its initial builds I couldn't find anything to calculate `PCA` so I had to go back to `numpy` or `sklearn`. I want to keep dependencies for my library as less as possible.
I know that these tests are easy fixes but it broke almost 60% of the test cases. Also it is very resource consuming with no direct `pip` packages for Travis (without CUDA support).

**Comment by markroxor** [comment]
Note to self - fix docs and update website accordingly.
Note to others - while you guys are on it, move your classes in the appropriate folders.

**Comment by souravsingh** [comment]
I suggest waiting until 1.0 release of PyTorch, which could fix some of the issues.
